### PR TITLE
Separate sys.COLORS and sys.fpath into their own files

### PR DESCRIPTION
**Pull request by colesbury**
The sys package forks processes when the package is required to
determine the OS and prefix. Unfortunately, due to a bug in OpenBLAS,
simulatenous calls to fork can deadlock. The torch7 and image packages
require sys at intialization, which now makes deadlocks much more common
when using Torch threads and OpenBLAS.

This moves sys.COLORS and sys.fpath into their own files which can be
required independently, so that torch7 and image don't have to require
all of sys and fork at initialization.

### CODE REVIEW

**Comment by soumith** [comment]
Wtf did i just read....

**Comment by lvdmaaten** [comment]
Deadlocks Soumith! Deadlocks everywhere!

**Comment by Saulzar** [comment]
I've been running into this problem or something similar when using the 'threads' package, I found that the issue was 'sys' being required somewhere in a chain of 'require' deadlocking.

I couldn't manage to reliably produce an isolated test case, but avoiding sys definitely avoided the issue and it only happens on one machine - I guess it must be something to do with the version of openblas installed?

**Comment by lvdmaaten** [comment]
Yeah I don't think that there is a fix for this problem as its root cause is in OpenBLAS. The preferred solution is to avoid OpenBLAS or, alternatively, avoid requiring `sys` when possible.

**Pull request merged**
